### ISSUE TITLE
Support for the ViaVersion Plugin

### ISSUE THREAD

**Issue by LukvonStrom** [filoghost/HolographicDisplaysPatch#2]
Hey, would it be possible to support the Plugin ViaVersion https://github.com/MylesIsCool/ViaVersion/ from @MylesIsCool as supposed in this ticket: https://github.com/MylesIsCool/ViaVersion/issues/20 ? 
Thanks in advance,

LukvonStrom

**Comment by Paulomart** [comment]
Fyi: ViaVersion offers a Api to check if a player uses the protocol hack. ViaVersion.getInstance().isPorted(Player).

**Comment by filoghost** [comment]
This plugin is no longer maintained or supported, sorry.
